name: editable_image
description: Flutter package for creating a fully customizable and editable image widget.
version: 0.2.0
homepage: https://github.com/BBarisKilic/Editable-Image

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  wechat_assets_picker: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
