# Copyright 2021 The EditableImage Author. All rights reserved.
# Use of this source code is governed by a Apache 2.0-style license
# that can be found in the LICENSE file.

name: editable_image
description: Flutter package for creating a fully customizable and editable image widget.
version: 1.1.0
homepage: https://github.com/BBarisKilic/Editable-Image

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  wechat_assets_picker: ^8.4.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter: null
