name: user_profile_1
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  # To add editable_image as a dependency to your application, add it like this:
  # editable_image: ^x.y.z
  editable_image:
    path: ../../
  flutter:
    sdk: flutter

dev_dependencies:

  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
